package de.saxsys.svgfx.css;

import de.saxsys.svgfx.css.core.CssStyle;
import javafx.scene.Node;
import org.junit.Assert;
import org.junit.Test;

/**
 * Created by Xyanid on 05.10.2015.
 */
public final class CssStyleTest {

    //region Fields

    private final String cssText = ".st0{fill:none;stroke:#808080;stroke-width:3;stroke-miterlimit:10;}";

    private final String cssDeclarationBlock = "fill:none;stroke:#808080;stroke-width:3;stroke-miterlimit:15;";

    private final String cssTextChanged = ".st0{fill:none;stroke:#808080;stroke-width:3;stroke-miterlimit:15;}";

    private final String cssTextWithComment = ".st0{fill:none;stroke:#808080;/*this is a comment*/stroke-width:3;stroke-miterlimit:10;}";

    private final String cssTextWithCommentAndCssCharacters = ".st0{fill:none;stroke:#808080;/*{\"this is ;:a string\";:}*/stroke-width:3;stroke-miterlimit:10;}";

    private final String cssTextWithString = ".st0{fill:none;stroke:\"#808080\";stroke-width:3;stroke-miterlimit:10;}";

    private final String cssTextWithStringAndCssCharacters = ".st0{fill:none;stroke:\";{ar;asd:j}:sda;asd:\";stroke-width:3;stroke-miterlimit:10;}";

    //endregion

    //region Tests

    /**
     * Parses a css text to create a css style.
     */
    @Test public void parseCssTextToCreateCssStyle() {

        CssStyle style = new CssStyle();

        style.setCssText(cssText);

        Assert.assertEquals(cssText, style.getCssText());
    }

    /**
     * Parses a css text which contains comments and also characters related to css parsing.
     * This will ensure that no character inside a string will interrupt the parsing.
     */
    @Test public void parseCssTextWithCommentAndCssCharactersToCreateCssStyle() {

        CssStyle style = new CssStyle();

        style.setCssText(cssTextWithComment);

        Assert.assertEquals(cssText, style.getCssText());

        style.setCssText(cssTextWithCommentAndCssCharacters);

        Assert.assertEquals(cssText, style.getCssText());
    }

    /**
     * Parses a css text which contains string indicators inside a property and also contains characters related to css parsing.
     * This will ensure that no character inside a string will interrupt the parsing.
     */
    @Test public void parseCssTextWithStringIndicatorsAndCssCharactersToCreateCssStyle() {

        CssStyle style = new CssStyle();

        style.setCssText(cssTextWithString);

        Assert.assertEquals(cssTextWithString, style.getCssText());

        style.setCssText(cssTextWithStringAndCssCharacters);

        Assert.assertEquals(cssTextWithStringAndCssCharacters, style.getCssText());
    }

    /**
     * Parses a css text and set a property of the css style afterwards, this ensures that the css text generated by the css style will be changed.
     */
    @Test public void parseCssTextToCreateCssStyleAndChangeCssPropertyAfterwards() {

        CssStyle style = new CssStyle();

        style.setCssText(cssText);

        Assert.assertEquals(cssText, style.getCssText());

        style.getCssStyleDeclaration().setCssText(cssDeclarationBlock);

        Assert.assertEquals(cssTextChanged, style.getCssText());

        style.getCssStyleDeclaration().getPropertyCSSValue("stroke-miterlimit").setCssText("10");

        Assert.assertEquals(cssText, style.getCssText());
    }

    //endregion
}
